# Run mediamtx from the project root

paths:
  stream0:
    runOnInit: >
      ffmpeg -re -stream_loop -1
      -i data/c1_5min.mp4
      -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes

  stream1:
    runOnInit: >
      ffmpeg -re -stream_loop -1
      -i data/c2_5min.mp4
      -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes

  stream2:
    runOnInit: >
      ffmpeg -re -stream_loop -1
      -i data/c3_5min.mp4
      -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
